// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqjkdmqcmhtfuvloqxht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxamtkbXFjbWh0ZnV2bG9xeGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTkxODIsImV4cCI6MjA3MjM5NTE4Mn0.JGwVcKpphzSjI8mibylbhZRNReRQBdzB_l9VQ1MrYqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});